import { RealEstate, Transaction } from "types";

export const MAP: Record<string, Record<number, string>> = {
  DealType: {
    0: "Купли-продажа",
    1: "Аренда",
  },
  Accommodation: {
    0: "Квартира",
    1: "Частный дом",
    2: "Таун-хаус",
    3: "Аппартаменты",
  },
} as const;

export const REVERSE_MAP: Record<string, Record<string, number>> = {
  DealType: {
    "Купли-продажа": 0,
    Аренда: 1,
  },
  Accommodation: {
    Квартира: 0,
    "Частный дом": 1,
    "Таун-хаус": 2,
    Аппартаменты: 3,
  },
};

export const ADS_COLUMNS = [
  {
    id: "Accommodation",
    name: "Тип недвижимости",
    template: (val: RealEstate) => MAP["Accommodation"][val.Accommodation],
  },
  {
    name: "Тип сделки",
    id: "DealType",
    template: (val: RealEstate) => MAP["DealType"][val.DealType],
  },
  {
    name: "Улица",
    id: "Street",
  },
  {
    name: "Номер дома",
    id: "HouseNumber",
  },
  {
    name: "Этаж",
    id: "Floor",
  },
  {
    name: "Этажей в доме",
    id: "FloorsCount",
  },
  {
    name: "Номер квартиры",
    id: "ApartmentNumber",
  },
  {
    name: "Число комнат",
    id: "RoomsCount",
  },
  {
    name: "Площадь",
    id: "TotalMeters",
  },
  {
    name: "Район",
    id: "District",
  },
  {
    name: "Станция метро",
    id: "Metro",
  },
  {
    name: "Дата публикации",
    id: "PublicationDate",
    template: (val: RealEstate) => val.PublicationDate.slice(0, 10),
  },
  {
    name: "Цена",
    id: "Price",
  },
];

export const TRANSACTIONS_COLUMNS = [
  {
    id: "AccommodationTypeName",
    name: "Тип недвижимости",
  },
  {
    name: "Тип сделки",
    id: "DealTypeName",
  },
  {
    name: "Агент",
    id: "AgentFullName",
  },
  {
    name: "Клиент",
    id: "ClientFullName",
  },
  {
    name: "Дата транзации",
    id: "TransactionDate",
    template: (val: Transaction) => val.TransactionDate.slice(0, 10),
  },
  {
    name: "Цена",
    id: "TransactionPrice",
  },
];

export const TRANSACTION_CREATE_COLUMNS = [
  {
    id: "DealTypeName",
  },
  {
    id: "AgentFullName",
  },
  {
    id: "ClientFullName",
  },
  {
    id: "TransactionPrice",
  },
];

export const CREATE_COLUMNS = [
  {
    id: "ApartmentNumber",
  },
  {
    id: "DealType",
  },
  {
    id: "Accommodation",
  },
  {
    id: "District",
  },
  {
    id: "Floor",
  },
  {
    id: "FloorsCount",
  },
  {
    id: "HouseNumber",
  },
  {
    id: "Metro",
  },
  {
    id: "RoomsCount",
  },
  {
    id: "Street",
  },
  {
    id: "TotalMeters",
  },
  {
    id: "Price",
  },
];

export const metro = [
  "Стрешнево",
  "Парк Победы",
  "Спортивная",
  "Алексеевская",
  "Дмитровская",
  "Пушкинская",
  "Калужская",
  "Строгино",
  "Павелецкая",
  "Аэропорт Внуково",
  "Воробьёвы горы",
  "Воронцовская",
  "Народное Ополчение",
  "Белорусская",
  "Фили",
  "Тульская",
  "Панфиловская",
  "Красный Балтиец",
  "Серпуховская",
  "Октябрьская",
  "Спартак",
  "Улица 1905 года",
  "Селигерская",
  "Шелепиха",
  "Ботанический сад",
  "Терехово ",
  "Карамышевская",
  "Зорге",
  "Владыкино",
  "Минская",
  "Братиславская",
  "Люблино",
  "Крымская",
  "Бутырская",
  "Смоленская",
  "Нижегородская",
  "Окружная",
  "Сокольники",
  "Рабочий посёлок",
  "Динамо",
  "Речной вокзал",
  "Саларьево",
  "Белокаменная",
  "Озёрная",
  "Прокшино",
  "Южная",
  "Коптево",
  "Свиблово",
  "Румянцево",
  "Улица Академика Янгеля",
  "Проспект Вернадского",
  "Коломенская",
  "Отрадное",
  "Хорошёвская",
  "Улица Скобелевская",
  "Сухаревская",
  "ВДНХ",
  "Университет",
  "Авиамоторная",
  "Царицыно",
  "Трикотажная",
  "Москва-Товарная",
  "Соколиная гора",
  "Рассказовка",
  "Бульвар Рокоссовского",
  "Зеленоград — Крюково",
  "Новохохловская",
  "Новаторская",
  "Крылатское",
  "Электрозаводская",
  "Коммунарка",
  "Юго-Западная",
  "Тропарёво",
  "Тёплый Стан",
  "Преображенская площадь",
  "Гражданская",
  "Ясенево",
  "Кутузовская",
  "Бунинская аллея",
  "Щёлковская",
  "Чертановская",
  "Октябрьское поле",
  "Бульвар Адмирала Ушакова",
  "Пятницкое шоссе",
  "Кленовый бульвар",
  "Лефортово",
  "Домодедовская",
  "Пенягино",
  "Сходненская",
  "Новогиреево",
  "Говорово",
  "Пражская",
  "Бауманская",
  "Давыдково",
  "Киевская",
  "Каховская",
  "Нагорная",
  "Бибирево",
  "Петровский Парк",
  "Тушинская",
  "Водный стадион",
  "Баррикадная",
  "Верхние Лихоборы",
  "Беговая",
  "Каширская",
  "Раменки",
  "Лесопарковая",
  "Хорошёво",
  "Улица Горчакова",
  "Очаково",
  "Нагатинская",
  "Новодачная",
  "Боровское шоссе",
  "Парк Культуры",
  "Площадь Ильича",
  "Толстопальцево",
  "Ломоносовский проспект",
  "Полянка",
  "Мичуринский проспект",
  "Академическая",
  "Аминьевская",
  "Варшавская",
  "Кожуховская",
  "Печатники",
  "Технопарк",
  "Маяковская",
  "Аэропорт",
  "Менделеевская",
  "Филатов Луг",
  "ЗИЛ",
  "Беляево",
  "Верхние котлы",
  "Хлебниково",
  "Алтуфьево",
  "Выхино",
  "Кузьминки",
  "Новоясеневская",
  "Багратионовская",
  "Косино",
  "Бабушкинская",
  "Нагатинский Затон",
  "Зябликово",
  "Солнцево",
  "Филёвский парк",
  "Медведково",
  "Москворечье",
  "Алма-Атинская",
  "Стахановская",
  "Сетунь",
  "Ольховая",
  "Сокол",
  "Таганская",
  "Некрасовка",
  "Марьина Роща",
  "Окская",
  "Шоссе Энтузиастов",
  "Пыхтино",
  "Автозаводская",
  "Моссельмаш",
  "Севастопольская",
  "Юго-Восточная",
  "Молжаниново",
  "Кантемировская",
  "Фонвизинская",
  "Нахимовский проспект",
  "Измайловская",
  "Улица Дмитриевского",
  "Беломорская",
  "Молодёжная",
  "Митино",
  "Кунцевская",
  "Рязанский проспект",
  "Курьяново",
  "Новопеределкино",
  "Яхромская",
  "Профсоюзная",
  "Силикатная",
  "Физтех",
  "Дубровка",
  "Борисово",
  "Грачёвская",
  "Матвеевская",
  "Вешняки",
  "Новокосино",
  "Улица Милашенкова",
  "Угрешская",
  "Жулебино",
  "Щербинка",
  "Остафьево",
  "Павшино",
  "Площадь трёх вокзалов",
  "Щукинская",
  "Перерва",
  "Бульвар Дмитрия Донского",
  "Красные ворота",
  "Курская",
  "Планерная",
  "Первомайская",
  "Победа",
  "Волгоградский проспект",
  "Крёкшино",
  "Кокошкино",
  "Битца",
  "Лобня",
  "Текстильщики",
  "Красный Строитель",
  "Депо",
  "Перово",
  "Лианозово",
  "Ховрино",
  "Марьино",
  "Мякинино",
  "Полежаевская",
  "Новые Черёмушки",
  "Шипиловская",
  "Улица Академика Королёва",
  "Цветной бульвар",
  "Кусково",
  "Сколково",
  "Шаболовская",
  "Савёловская",
  "ЦСКА",
  "Арбатская",
  "Коньково",
  "Подольск",
  "Волоколамская",
  "Петровско-Разумовская",
  "Новоподрезково",
  "Подрезково",
  "Измайлово",
  "Калитники",
  "Партизанская",
  "Рижская",
];

export const clients = [
  {
    FIELD1: 0,
    client_id: 1,
    first_name: "Александр",
    patronymic: "Игоревич",
    last_name: "Лебедев",
  },
  {
    FIELD1: 1,
    client_id: 2,
    first_name: "Ольга",
    patronymic: "Валентиновна",
    last_name: "Сидорова",
  },
  {
    FIELD1: 2,
    client_id: 3,
    first_name: "Дмитрий",
    patronymic: "Сергеевич",
    last_name: "Шестаков",
  },
  {
    FIELD1: 3,
    client_id: 4,
    first_name: "Екатерина",
    patronymic: "Анатольевна",
    last_name: "Полякова",
  },
  {
    FIELD1: 4,
    client_id: 5,
    first_name: "Максим",
    patronymic: "Валерьевич",
    last_name: "Федотов",
  },
  {
    FIELD1: 5,
    client_id: 6,
    first_name: "Ирина",
    patronymic: "Александровна",
    last_name: "Никитина",
  },
  {
    FIELD1: 6,
    client_id: 7,
    first_name: "Антонина",
    patronymic: "Владимировна",
    last_name: "Морозова",
  },
  {
    FIELD1: 7,
    client_id: 8,
    first_name: "Павел",
    patronymic: "Юрьевич",
    last_name: "Куликов",
  },
  {
    FIELD1: 8,
    client_id: 9,
    first_name: "Татьяна",
    patronymic: "Алексеевна",
    last_name: "Горбунова",
  },
  {
    FIELD1: 9,
    client_id: 10,
    first_name: "Артем",
    patronymic: "Андреевич",
    last_name: "Руднев",
  },
  {
    FIELD1: 10,
    client_id: 11,
    first_name: "Елена",
    patronymic: "Петровна",
    last_name: "Лисина",
  },
  {
    FIELD1: 11,
    client_id: 12,
    first_name: "Никита",
    patronymic: "Валерьевич",
    last_name: "Чернов",
  },
  {
    FIELD1: 12,
    client_id: 13,
    first_name: "Анастасия",
    patronymic: "Станиславовна",
    last_name: "Петрова",
  },
  {
    FIELD1: 13,
    client_id: 14,
    first_name: "Владимир",
    patronymic: "Дмитриевич",
    last_name: "Лапин",
  },
  {
    FIELD1: 14,
    client_id: 15,
    first_name: "Юлия",
    patronymic: "Игоревна",
    last_name: "Семенова",
  },
  {
    FIELD1: 15,
    client_id: 16,
    first_name: "Станислав",
    patronymic: "Анатольевич",
    last_name: "Миронов",
  },
  {
    FIELD1: 16,
    client_id: 17,
    first_name: "Евгения",
    patronymic: "Александровна",
    last_name: "Беляева",
  },
  {
    FIELD1: 17,
    client_id: 18,
    first_name: "Игорь",
    patronymic: "Викторович",
    last_name: "Ларин",
  },
  {
    FIELD1: 18,
    client_id: 19,
    first_name: "Светлана",
    patronymic: "Сергеевна",
    last_name: "Козлова",
  },
  {
    FIELD1: 19,
    client_id: 20,
    first_name: "Артур",
    patronymic: "Александрович",
    last_name: "Федосеев",
  },
  {
    FIELD1: 20,
    client_id: 21,
    first_name: "Мария",
    patronymic: "Валерьевна",
    last_name: "Рябова",
  },
  {
    FIELD1: 21,
    client_id: 22,
    first_name: "Владислав",
    patronymic: "Игнатьевич",
    last_name: "Баранов",
  },
  {
    FIELD1: 22,
    client_id: 23,
    first_name: "Алла",
    patronymic: "Анатольевна",
    last_name: "Григорьева",
  },
  {
    FIELD1: 23,
    client_id: 24,
    first_name: "Роман",
    patronymic: "Викторович",
    last_name: "Титов",
  },
  {
    FIELD1: 24,
    client_id: 25,
    first_name: "Анна",
    patronymic: "Васильевна",
    last_name: "Колесникова",
  },
  {
    FIELD1: 25,
    client_id: 26,
    first_name: "Кирилл",
    patronymic: "Андреевич",
    last_name: "Широков",
  },
  {
    FIELD1: 26,
    client_id: 27,
    first_name: "Оксана",
    patronymic: "Владимировна",
    last_name: "Зайцева",
  },
  {
    FIELD1: 27,
    client_id: 28,
    first_name: "Денис",
    patronymic: "Алексеевич",
    last_name: "Панов",
  },
  {
    FIELD1: 28,
    client_id: 29,
    first_name: "Елена",
    patronymic: "Ярославовна",
    last_name: "Федорова",
  },
  {
    FIELD1: 29,
    client_id: 30,
    first_name: "Арсений",
    patronymic: "Станиславович",
    last_name: "Крылов",
  },
  {
    FIELD1: 30,
    client_id: 31,
    first_name: "Милана",
    patronymic: "Васильевна",
    last_name: "Соколова",
  },
  {
    FIELD1: 31,
    client_id: 32,
    first_name: "Валентин",
    patronymic: "Викторович",
    last_name: "Шевцов",
  },
  {
    FIELD1: 32,
    client_id: 33,
    first_name: "Алёна",
    patronymic: "Игоревна",
    last_name: "Жукова",
  },
  {
    FIELD1: 33,
    client_id: 34,
    first_name: "Игнатий",
    patronymic: "Валентинович",
    last_name: "Комаров",
  },
  {
    FIELD1: 34,
    client_id: 35,
    first_name: "София",
    patronymic: "Анатольевна",
    last_name: "Пономарева",
  },
  {
    FIELD1: 35,
    client_id: 36,
    first_name: "Лев",
    patronymic: "Артемович",
    last_name: "Горбачев",
  },
  {
    FIELD1: 36,
    client_id: 37,
    first_name: "Юлия",
    patronymic: "Алексеевна",
    last_name: "Назарова",
  },
  {
    FIELD1: 37,
    client_id: 38,
    first_name: "Михаил",
    patronymic: "Валерьевич",
    last_name: "Сухарев",
  },
  {
    FIELD1: 38,
    client_id: 39,
    first_name: "Вероника",
    patronymic: "Игоревна",
    last_name: "Мельникова",
  },
  {
    FIELD1: 39,
    client_id: 40,
    first_name: "Егор",
    patronymic: "Андреевич",
    last_name: "Беляков",
  },
  {
    FIELD1: 40,
    client_id: 41,
    first_name: "Ангелина",
    patronymic: "Артемовна",
    last_name: "Попова",
  },
  {
    FIELD1: 41,
    client_id: 42,
    first_name: "Степан",
    patronymic: "Александрович",
    last_name: "Лебедев",
  },
  {
    FIELD1: 42,
    client_id: 43,
    first_name: "Алла",
    patronymic: "Валентиновна",
    last_name: "Дмитриева",
  },
  {
    FIELD1: 43,
    client_id: 44,
    first_name: "Виктор",
    patronymic: "Викторович",
    last_name: "Романов",
  },
  {
    FIELD1: 44,
    client_id: 45,
    first_name: "Анастасия",
    patronymic: "Анатольевна",
    last_name: "Богданова",
  },
  {
    FIELD1: 45,
    client_id: 46,
    first_name: "Павел",
    patronymic: "Валерьевич",
    last_name: "Семенов",
  },
  {
    FIELD1: 46,
    client_id: 47,
    first_name: "Элина",
    patronymic: "Сергеевна",
    last_name: "Федотова",
  },
  {
    FIELD1: 47,
    client_id: 48,
    first_name: "Сергей",
    patronymic: "Игоревич",
    last_name: "Кузнецов",
  },
  {
    FIELD1: 48,
    client_id: 49,
    first_name: "Ольга",
    patronymic: "Викторовна",
    last_name: "Тихонова",
  },
  {
    FIELD1: 49,
    client_id: 50,
    first_name: "Артур",
    patronymic: "Анатольевич",
    last_name: "Головин",
  },
  {
    FIELD1: 50,
    client_id: 51,
    first_name: "Надежда",
    patronymic: "Сергеевна",
    last_name: "Полякова",
  },
  {
    FIELD1: 51,
    client_id: 52,
    first_name: "Илья",
    patronymic: "Александрович",
    last_name: "Новиков",
  },
  {
    FIELD1: 52,
    client_id: 53,
    first_name: "Евгения",
    patronymic: "Валентиновна",
    last_name: "Ларина",
  },
  {
    FIELD1: 53,
    client_id: 54,
    first_name: "Даниил",
    patronymic: "Артемович",
    last_name: "Козлов",
  },
  {
    FIELD1: 54,
    client_id: 55,
    first_name: "Людмила",
    patronymic: "Анатольевна",
    last_name: "Игнатьева",
  },
  {
    FIELD1: 55,
    client_id: 56,
    first_name: "Руслан",
    patronymic: "Валерьевич",
    last_name: "Карпов",
  },
  {
    FIELD1: 56,
    client_id: 57,
    first_name: "Тамара",
    patronymic: "Игоревна",
    last_name: "Шестакова",
  },
  {
    FIELD1: 57,
    client_id: 58,
    first_name: "Артем",
    patronymic: "Викторович",
    last_name: "Федосеев",
  },
  {
    FIELD1: 58,
    client_id: 59,
    first_name: "Лилия",
    patronymic: "Александровна",
    last_name: "Лисина",
  },
  {
    FIELD1: 59,
    client_id: 60,
    first_name: "Владислав",
    patronymic: "Степанович",
    last_name: "Горбунов",
  },
  {
    FIELD1: 60,
    client_id: 61,
    first_name: "Екатерина",
    patronymic: "Артемовна",
    last_name: "Куликова",
  },
  {
    FIELD1: 61,
    client_id: 62,
    first_name: "Андрей",
    patronymic: "Игнатьевич",
    last_name: "Колесников",
  },
  {
    FIELD1: 62,
    client_id: 63,
    first_name: "Дарья",
    patronymic: "Валентиновна",
    last_name: "Степанова",
  },
  {
    FIELD1: 63,
    client_id: 64,
    first_name: "Григорий",
    patronymic: "Анатольевич",
    last_name: "Миронов",
  },
  {
    FIELD1: 64,
    client_id: 65,
    first_name: "Марина",
    patronymic: "Васильевна",
    last_name: "Руднева",
  },
  {
    FIELD1: 65,
    client_id: 66,
    first_name: "Иван",
    patronymic: "Викторович",
    last_name: "Ларин",
  },
  {
    FIELD1: 66,
    client_id: 67,
    first_name: "Вероника",
    patronymic: "Александровна",
    last_name: "Петрова",
  },
  {
    FIELD1: 67,
    client_id: 68,
    first_name: "Станислав",
    patronymic: "Артемович",
    last_name: "Тимофеев",
  },
  {
    FIELD1: 68,
    client_id: 69,
    first_name: "Юлия",
    patronymic: "Сергеевна",
    last_name: "Федосеева",
  },
  {
    FIELD1: 69,
    client_id: 70,
    first_name: "Антон",
    patronymic: "Анатольевич",
    last_name: "Петров",
  },
  {
    FIELD1: 70,
    client_id: 71,
    first_name: "Анна",
    patronymic: "Валентиновна",
    last_name: "Григорьева",
  },
  {
    FIELD1: 71,
    client_id: 72,
    first_name: "Максим",
    patronymic: "Викторович",
    last_name: "Титов",
  },
  {
    FIELD1: 72,
    client_id: 73,
    first_name: "Лидия",
    patronymic: "Артемовна",
    last_name: "Колесникова",
  },
  {
    FIELD1: 73,
    client_id: 74,
    first_name: "Роман",
    patronymic: "Сергеевич",
    last_name: "Широков",
  },
  {
    FIELD1: 74,
    client_id: 75,
    first_name: "Нина",
    patronymic: "Игоревна",
    last_name: "Зайцева",
  },
  {
    FIELD1: 75,
    client_id: 76,
    first_name: "Денис",
    patronymic: "Валентинович",
    last_name: "Панов",
  },
  {
    FIELD1: 76,
    client_id: 77,
    first_name: "Ксения",
    patronymic: "Андреевна",
    last_name: "Федорова",
  },
  {
    FIELD1: 77,
    client_id: 78,
    first_name: "Валерий",
    patronymic: "Анатольевич",
    last_name: "Крылов",
  },
  {
    FIELD1: 78,
    client_id: 79,
    first_name: "Маргарита",
    patronymic: "Артемовна",
    last_name: "Соколова",
  },
  {
    FIELD1: 79,
    client_id: 80,
    first_name: "Аркадий",
    patronymic: "Станиславович",
    last_name: "Шевцов",
  },
  {
    FIELD1: 80,
    client_id: 81,
    first_name: "Наталья",
    patronymic: "Васильевна",
    last_name: "Жукова",
  },
  {
    FIELD1: 81,
    client_id: 82,
    first_name: "Степан",
    patronymic: "Викторович",
    last_name: "Комаров",
  },
  {
    FIELD1: 82,
    client_id: 83,
    first_name: "Вероника",
    patronymic: "Игнатьевна",
    last_name: "Пономарева",
  },
  {
    FIELD1: 83,
    client_id: 84,
    first_name: "Игорь",
    patronymic: "Валентинович",
    last_name: "Горбачев",
  },
  {
    FIELD1: 84,
    client_id: 85,
    first_name: "Алиса",
    patronymic: "Игоревна",
    last_name: "Назарова",
  },
  {
    FIELD1: 85,
    client_id: 86,
    first_name: "Александр",
    patronymic: "Валерьевич",
    last_name: "Сухарев",
  },
  {
    FIELD1: 86,
    client_id: 87,
    first_name: "Дарина",
    patronymic: "Викторовна",
    last_name: "Мельникова",
  },
  {
    FIELD1: 87,
    client_id: 88,
    first_name: "Артем",
    patronymic: "Анатольевич",
    last_name: "Беляков",
  },
  {
    FIELD1: 88,
    client_id: 89,
    first_name: "София",
    patronymic: "Артемовна",
    last_name: "Попова",
  },
  {
    FIELD1: 89,
    client_id: 90,
    first_name: "Иван",
    patronymic: "Сергеевич",
    last_name: "Лебедев",
  },
  {
    FIELD1: 90,
    client_id: 91,
    first_name: "Александра",
    patronymic: "Валентиновна",
    last_name: "Дмитриева",
  },
  {
    FIELD1: 91,
    client_id: 92,
    first_name: "Максим",
    patronymic: "Александрович",
    last_name: "Тихонов",
  },
  {
    FIELD1: 92,
    client_id: 93,
    first_name: "Ольга",
    patronymic: "Сергеевна",
    last_name: "Богданова",
  },
  {
    FIELD1: 93,
    client_id: 94,
    first_name: "Владислав",
    patronymic: "Игоревич",
    last_name: "Семенов",
  },
  {
    FIELD1: 94,
    client_id: 95,
    first_name: "Вероника",
    patronymic: "Валентиновна",
    last_name: "Федотова",
  },
  {
    FIELD1: 95,
    client_id: 96,
    first_name: "Дмитрий",
    patronymic: "Валерьевич",
    last_name: "Кузнецов",
  },
  {
    FIELD1: 96,
    client_id: 97,
    first_name: "Елена",
    patronymic: "Александровна",
    last_name: "Тихонова",
  },
  {
    FIELD1: 97,
    client_id: 98,
    first_name: "Сергей",
    patronymic: "Валентинович",
    last_name: "Карпов",
  },
  {
    FIELD1: 98,
    client_id: 99,
    first_name: "Маргарита",
    patronymic: "Станиславовна",
    last_name: "Шестакова",
  },
  {
    FIELD1: 99,
    client_id: 100,
    first_name: "Самуил",
    patronymic: "Абрамович",
    last_name: "Шустер",
  },
  {
    FIELD1: 100,
    client_id: 101,
    first_name: "Анна",
    patronymic: "Иосифовна",
    last_name: "Левитан",
  },
  {
    FIELD1: 101,
    client_id: 102,
    first_name: "Яков",
    patronymic: "Леонидович",
    last_name: "Гурвич",
  },
  {
    FIELD1: 102,
    client_id: 103,
    first_name: "Лариса",
    patronymic: "Аркадьевна",
    last_name: "Левин",
  },
  {
    FIELD1: 103,
    client_id: 104,
    first_name: "Мендель",
    patronymic: "Аронович",
    last_name: "Лейбов",
  },
  {
    FIELD1: 104,
    client_id: 105,
    first_name: "Ривка",
    patronymic: "Леонидовна",
    last_name: "Гольдберг",
  },
  {
    FIELD1: 105,
    client_id: 106,
    first_name: "Михаил",
    patronymic: "Абрамович",
    last_name: "Розенберг",
  },
  {
    FIELD1: 106,
    client_id: 107,
    first_name: "Ева",
    patronymic: "Яковлевна",
    last_name: "Шапиро",
  },
  {
    FIELD1: 107,
    client_id: 108,
    first_name: "Исаак",
    patronymic: "Лазаревич",
    last_name: "Фрейдман",
  },
  {
    FIELD1: 108,
    client_id: 109,
    first_name: "Лилия",
    patronymic: "Иосифовна",
    last_name: "Абрамова",
  },
  {
    FIELD1: 109,
    client_id: 110,
    first_name: "Борис",
    patronymic: "Леонидович",
    last_name: "Кац",
  },
  {
    FIELD1: 110,
    client_id: 111,
    first_name: "Анна",
    patronymic: "Аркадьевна",
    last_name: "Левитан",
  },
  {
    FIELD1: 111,
    client_id: 112,
    first_name: "Яков",
    patronymic: "Маркович",
    last_name: "Гурвич",
  },
  {
    FIELD1: 112,
    client_id: 113,
    first_name: "Мария",
    patronymic: "Исааковна",
    last_name: "Шустер",
  },
  {
    FIELD1: 113,
    client_id: 114,
    first_name: "Лев",
    patronymic: "Яковлевич",
    last_name: "Левин",
  },
  {
    FIELD1: 114,
    client_id: 115,
    first_name: "Ирина",
    patronymic: "Абрамовна",
    last_name: "Лейбова",
  },
  {
    FIELD1: 115,
    client_id: 116,
    first_name: "Максим",
    patronymic: "Леонидович",
    last_name: "Розенберг",
  },
  {
    FIELD1: 116,
    client_id: 117,
    first_name: "Роза",
    patronymic: "Яковлевна",
    last_name: "Шапиро",
  },
  {
    FIELD1: 117,
    client_id: 118,
    first_name: "Марк",
    patronymic: "Аронович",
    last_name: "Фрейдман",
  },
  {
    FIELD1: 118,
    client_id: 119,
    first_name: "Александра",
    patronymic: "Иосифовна",
    last_name: "Левин",
  },
  {
    FIELD1: 119,
    client_id: 120,
    first_name: "Самуил",
    patronymic: "Леонидович",
    last_name: "Шустер",
  },
  {
    FIELD1: 120,
    client_id: 121,
    first_name: "Елена",
    patronymic: "Яковлевна",
    last_name: "Гурвич",
  },
  {
    FIELD1: 121,
    client_id: 122,
    first_name: "Давид",
    patronymic: "Маркович",
    last_name: "Розенберг",
  },
  {
    FIELD1: 122,
    client_id: 123,
    first_name: "Алексей",
    patronymic: "Леонидович",
    last_name: "Шапиро",
  },
  {
    FIELD1: 123,
    client_id: 124,
    first_name: "Светлана",
    patronymic: "Аркадьевна",
    last_name: "Левин",
  },
  {
    FIELD1: 124,
    client_id: 125,
    first_name: "Исаак",
    patronymic: "Яковлевич",
    last_name: "Левитан",
  },
  {
    FIELD1: 125,
    client_id: 126,
    first_name: "Рахиль",
    patronymic: "Менделевна",
    last_name: "Лейбова",
  },
  {
    FIELD1: 126,
    client_id: 127,
    first_name: "Артур",
    patronymic: "Исаакович",
    last_name: "Гольдберг",
  },
  {
    FIELD1: 127,
    client_id: 128,
    first_name: "Лия",
    patronymic: "Леонидовна",
    last_name: "Шустер",
  },
  {
    FIELD1: 128,
    client_id: 129,
    first_name: "Марк",
    patronymic: "Лазаревич",
    last_name: "Левитан",
  },
];

export const agents = [
  {
    FIELD1: 0,
    agent_id: 1,
    first_name: "Яков",
    patronymic: "Моисеевич",
    last_name: "Абрамов",
  },
  {
    FIELD1: 1,
    agent_id: 2,
    first_name: "Рахиль",
    patronymic: "Ароновна",
    last_name: "Голдштейн",
  },
  {
    FIELD1: 2,
    agent_id: 3,
    first_name: "Шимон",
    patronymic: "Левович",
    last_name: "Кац",
  },
  {
    FIELD1: 3,
    agent_id: 4,
    first_name: "Мириам",
    patronymic: "Исааковна",
    last_name: "Левин",
  },
  {
    FIELD1: 4,
    agent_id: 5,
    first_name: "Мендель",
    patronymic: "Яковлевич",
    last_name: "Шапиро",
  },
  {
    FIELD1: 5,
    agent_id: 6,
    first_name: "Леа",
    patronymic: "Борисовна",
    last_name: "Розенберг",
  },
  {
    FIELD1: 6,
    agent_id: 7,
    first_name: "Марк",
    patronymic: "Лазаревич",
    last_name: "Каган",
  },
  {
    FIELD1: 7,
    agent_id: 8,
    first_name: "Алла",
    patronymic: "Яковлевна",
    last_name: "Фрейдман",
  },
  {
    FIELD1: 8,
    agent_id: 9,
    first_name: "Артур",
    patronymic: "Леонидович",
    last_name: "Лейбов",
  },
  {
    FIELD1: 9,
    agent_id: 10,
    first_name: "Сара",
    patronymic: "Моисеевна",
    last_name: "Абрамова",
  },
  {
    FIELD1: 10,
    agent_id: 11,
    first_name: "Иосиф",
    patronymic: "Аркадьевич",
    last_name: "Левитан",
  },
  {
    FIELD1: 11,
    agent_id: 12,
    first_name: "Роза",
    patronymic: "Ароновна",
    last_name: "Голдберг",
  },
  {
    FIELD1: 12,
    agent_id: 13,
    first_name: "Максим",
    patronymic: "Исаакович",
    last_name: "Рейхман",
  },
  {
    FIELD1: 13,
    agent_id: 14,
    first_name: "Лилия",
    patronymic: "Лазаревна",
    last_name: "Кац",
  },
  {
    FIELD1: 14,
    agent_id: 15,
    first_name: "Александр",
    patronymic: "Яковлевич",
    last_name: "Фрейдман",
  },
  {
    FIELD1: 15,
    agent_id: 16,
    first_name: "Марина",
    patronymic: "Леонидовна",
    last_name: "Лейбова",
  },
  {
    FIELD1: 16,
    agent_id: 17,
    first_name: "Лев",
    patronymic: "Лазаревич",
    last_name: "Гурвич",
  },
  {
    FIELD1: 17,
    agent_id: 18,
    first_name: "Тамара",
    patronymic: "Яковлевна",
    last_name: "Шапиро",
  },
  {
    FIELD1: 18,
    agent_id: 19,
    first_name: "Лев",
    patronymic: "Лазаревич",
    last_name: "Абрамов",
  },
  {
    FIELD1: 19,
    agent_id: 20,
    first_name: "Маргарита",
    patronymic: "Исааковна",
    last_name: "Розенберг",
  },
  {
    FIELD1: 20,
    agent_id: 21,
    first_name: "Никита",
    patronymic: "Игнатьевич",
    last_name: "Головин",
  },
  {
    FIELD1: 21,
    agent_id: 22,
    first_name: "Виктория",
    patronymic: "Сергеевна",
    last_name: "Полякова",
  },
  {
    FIELD1: 22,
    agent_id: 23,
    first_name: "Анатолий",
    patronymic: "Викторович",
    last_name: "Комаров",
  },
  {
    FIELD1: 23,
    agent_id: 24,
    first_name: "Евгения",
    patronymic: "Валерьевна",
    last_name: "Соколова",
  },
  {
    FIELD1: 24,
    agent_id: 25,
    first_name: "Роман",
    patronymic: "Артемович",
    last_name: "Горбачев",
  },
  {
    FIELD1: 25,
    agent_id: 26,
    first_name: "Татьяна",
    patronymic: "Игоревна",
    last_name: "Назарова",
  },
  {
    FIELD1: 26,
    agent_id: 27,
    first_name: "Артем",
    patronymic: "Викентьевич",
    last_name: "Сухарев",
  },
  {
    FIELD1: 27,
    agent_id: 28,
    first_name: "Алёна",
    patronymic: "Валентиновна",
    last_name: "Мельникова",
  },
  {
    FIELD1: 28,
    agent_id: 29,
    first_name: "Максим",
    patronymic: "Игнатьевич",
    last_name: "Беляков",
  },
  {
    FIELD1: 29,
    agent_id: 30,
    first_name: "Диана",
    patronymic: "Станиславовна",
    last_name: "Попова",
  },
  {
    FIELD1: 30,
    agent_id: 31,
    first_name: "Артем",
    patronymic: "Сергеевич",
    last_name: "Лебедев",
  },
  {
    FIELD1: 31,
    agent_id: 32,
    first_name: "Валентина",
    patronymic: "Валентиновна",
    last_name: "Дмитриева",
  },
  {
    FIELD1: 32,
    agent_id: 33,
    first_name: "Павел",
    patronymic: "Александрович",
    last_name: "Тихонов",
  },
  {
    FIELD1: 33,
    agent_id: 34,
    first_name: "Анастасия",
    patronymic: "Валентиновна",
    last_name: "Богданова",
  },
  {
    FIELD1: 34,
    agent_id: 35,
    first_name: "Влад",
    patronymic: "Валерьевич",
    last_name: "Семенов",
  },
  {
    FIELD1: 35,
    agent_id: 36,
    first_name: "Елена",
    patronymic: "Андреевна",
    last_name: "Федотова",
  },
  {
    FIELD1: 36,
    agent_id: 37,
    first_name: "Алексей",
    patronymic: "Александрович",
    last_name: "Кузнецов",
  },
  {
    FIELD1: 37,
    agent_id: 38,
    first_name: "Юлия",
    patronymic: "Сергеевна",
    last_name: "Тихонова",
  },
  {
    FIELD1: 38,
    agent_id: 39,
    first_name: "Станислав",
    patronymic: "Артемович",
    last_name: "Карпов",
  },
  {
    FIELD1: 39,
    agent_id: 40,
    first_name: "Лилия",
    patronymic: "Игоревна",
    last_name: "Шестакова",
  },
  {
    FIELD1: 40,
    agent_id: 41,
    first_name: "Илья",
    patronymic: "Викторович",
    last_name: "Головин",
  },
  {
    FIELD1: 41,
    agent_id: 42,
    first_name: "Оксана",
    patronymic: "Анатольевна",
    last_name: "Полякова",
  },
  {
    FIELD1: 42,
    agent_id: 43,
    first_name: "Сергей",
    patronymic: "Викентьевич",
    last_name: "Комаров",
  },
  {
    FIELD1: 43,
    agent_id: 44,
    first_name: "Маргарита",
    patronymic: "Валерьевна",
    last_name: "Соколова",
  },
  {
    FIELD1: 44,
    agent_id: 45,
    first_name: "Денис",
    patronymic: "Артемович",
    last_name: "Горбачев",
  },
  {
    FIELD1: 45,
    agent_id: 46,
    first_name: "Алла",
    patronymic: "Игнатьевна",
    last_name: "Назарова",
  },
  {
    FIELD1: 46,
    agent_id: 47,
    first_name: "Игнат",
    patronymic: "Викентьевич",
    last_name: "Сухарев",
  },
  {
    FIELD1: 47,
    agent_id: 48,
    first_name: "Елизавета",
    patronymic: "Валентиновна",
    last_name: "Мельникова",
  },
  {
    FIELD1: 48,
    agent_id: 49,
    first_name: "Аркадий",
    patronymic: "Валерьевич",
    last_name: "Беляков",
  },
  {
    FIELD1: 49,
    agent_id: 50,
    first_name: "Мария",
    patronymic: "Станиславовна",
    last_name: "Попова",
  },
  {
    FIELD1: 50,
    agent_id: 51,
    first_name: "Игорь",
    patronymic: "Сергеевич",
    last_name: "Лебедев",
  },
  {
    FIELD1: 51,
    agent_id: 52,
    first_name: "Анна",
    patronymic: "Викторовна",
    last_name: "Дмитриева",
  },
  {
    FIELD1: 52,
    agent_id: 53,
    first_name: "Антон",
    patronymic: "Валентинович",
    last_name: "Тихонов",
  },
  {
    FIELD1: 53,
    agent_id: 54,
    first_name: "Кристина",
    patronymic: "Артемовна",
    last_name: "Богданова",
  },
  {
    FIELD1: 54,
    agent_id: 55,
    first_name: "Дмитрий",
    patronymic: "Викентьевич",
    last_name: "Семенов",
  },
  {
    FIELD1: 55,
    agent_id: 56,
    first_name: "Екатерина",
    patronymic: "Сергеевна",
    last_name: "Федотова",
  },
  {
    FIELD1: 56,
    agent_id: 57,
    first_name: "Владислав",
    patronymic: "Андреевич",
    last_name: "Кузнецов",
  },
  {
    FIELD1: 57,
    agent_id: 58,
    first_name: "Ольга",
    patronymic: "Валентиновна",
    last_name: "Тихонова",
  },
  {
    FIELD1: 58,
    agent_id: 59,
    first_name: "Николай",
    patronymic: "Викторович",
    last_name: "Карпов",
  },
  {
    FIELD1: 59,
    agent_id: 60,
    first_name: "Анна",
    patronymic: "Станиславовна",
    last_name: "Шестакова",
  },
  {
    FIELD1: 60,
    agent_id: 61,
    first_name: "Валерий",
    patronymic: "Сергеевич",
    last_name: "Головин",
  },
  {
    FIELD1: 61,
    agent_id: 62,
    first_name: "Арина",
    patronymic: "Игоревна",
    last_name: "Полякова",
  },
  {
    FIELD1: 62,
    agent_id: 63,
    first_name: "Александр",
    patronymic: "Анатольевич",
    last_name: "Комаров",
  },
  {
    FIELD1: 63,
    agent_id: 64,
    first_name: "Евгения",
    patronymic: "Валентиновна",
    last_name: "Соколова",
  },
  {
    FIELD1: 64,
    agent_id: 65,
    first_name: "Игорь",
    patronymic: "Артемович",
    last_name: "Горбачев",
  },
  {
    FIELD1: 65,
    agent_id: 66,
    first_name: "Юлия",
    patronymic: "Игнатьевна",
    last_name: "Назарова",
  },
  {
    FIELD1: 66,
    agent_id: 67,
    first_name: "Андрей",
    patronymic: "Викентьевич",
    last_name: "Сухарев",
  },
  {
    FIELD1: 67,
    agent_id: 68,
    first_name: "Екатерина",
    patronymic: "Валерьевна",
    last_name: "Мельникова",
  },
  {
    FIELD1: 68,
    agent_id: 69,
    first_name: "Максим",
    patronymic: "Станиславович",
    last_name: "Беляков",
  },
  {
    FIELD1: 69,
    agent_id: 70,
    first_name: "Светлана",
    patronymic: "Валентиновна",
    last_name: "Попова",
  },
];
